name = "PhyloTools"
uuid = "5597d80c-db21-43ac-b072-363bf70c4656"
authors = ["Leonardo Di Bari"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
